name = "pascaliske-dev"
main = "workers/index.ts"
compatibility_date = "2023-03-31"
workers_dev = true

[site]
bucket = "./dist/pascaliske-dev/browser"
exclude = ["stats.json"]

[build]
command = ""

[env.production]
name = "pascaliske-dev-production"
route = "pascaliske.dev/*"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "pascaliske-dev-staging"
route = "next.pascaliske.dev/*"
vars = { ENVIRONMENT = "staging" }
