export const enum Tags {
    ANGULAR = 'Angular',
    ANSIBLE = 'Ansible',
    AWS = 'AWS',
    BASH = 'Bash',
    CLOUDFLARE = 'Cloudflare',
    DOCKER = 'Docker',
    FLUX = 'Flux',
    GCP = 'GCP',
    GITHUB_ACTIONS = 'GitHub Actions',
    GITLAB_CI = 'GitLab CI',
    GOLANG = 'Go',
    GRAFANA = 'Grafana',
    HELM = 'Helm',
    KUBERNETES = 'Kubernetes',
    NODEJS = 'Node.js',
    OCI = 'OCI',
    PROMETHEUS = 'Prometheus',
    TERRAFORM = 'Terraform',
    TYPESCRIPT = 'TypeScript/JavaScript',
    VSPHERE = 'VMware vSphere',
}
