name: Linting
on: push

jobs:
  lint-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v4

      # setup taskfile
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup terraform
      - uses: hashicorp/setup-terraform@v3

      # setup tflint
      - uses: terraform-linters/setup-tflint@v4

      # init terraform
      - name: Init Terraform
        run: task tf:init -- -backend=false

      # validate terraform
      - name: Validate Terraform
        run: task tf:validate

      # lint terraform
      - name: Lint Terraform
        run: task tf:lint

  lint-angular:
    name: Angular
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v4

      # setup node
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      # lint angular
      - name: Lint
        run: yarn run lint
