name: Deploy Staging
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://next.pascaliske.dev
    steps:
      # checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # prepare
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # test
      - run: yarn run lint

      # build
      - run: yarn run build
      - run: yarn run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_REPO_SLUG: ${{ env.GITHUB_REPOSITORY }}
          CI_COMMIT_SHA: ${{ env.GITHUB_SHA }}
          CI_BRANCH: ${{ env.GITHUB_REF }}

      # deploy
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: staging
        env:
          CF_ZONE_ID: '${{ secrets.CF_ZONE_ID }}'

      # clear cache
      - uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CF_API_TOKEN }}
