name: Deploy Staging
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://next.pascaliske.dev
    steps:
      # checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # setup node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # build
      - name: Build application
        run: yarn run prerender

      # deploy
      - uses: cloudflare/wrangler-action@v3.4.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: staging
          secrets: |
            AUTH_USERNAME
            AUTH_PASSWORD
        env:
          CF_ZONE_ID: '${{ secrets.CF_ZONE_ID }}'
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}

      # clear cache
      - uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CF_API_TOKEN }}
